app:
  env: local
  port: 8888
  app_name: 枕楼管家
  app_url: http://localhost

log:
  is_console: true
  path: ../logs
  max_size: 10
  max_backups: 10
  max_age: 7
  level: 1

order_db:
  driver: mysql # 数据库驱动
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: order # 数据库名称
  username: root # 用户名
  password: 123456 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

